#!/usr/bin/env bash
# installs a nginx on web-01

sudo apt install nginx

sudo service nginx start

sudo echo 'server {\n    listen 80;\n    server_name _;\n\n    location / {\n        return 200 "Hello World!\n";\n    }\n}\n' > /etc/nginx/sites-available/default

# sudo nginx -t # checks the status

sudo service nginx restart
