#!/usr/bin/env bash
# installs a nginx on web-01

sudo apt update

sudo apt install -y nginx

sudo service nginx start

sudo echo "Hello World!" | sudo tee /var/www/html/index.html

# sudo nginx -t # checks the status

sudo service nginx restart
