#!/usr/bin/env bash
# You answer file should be a Bash script containing commands
# to automatically configure a Ubuntu machine
# Using what you did with 1-install_nginx_web_server,
# write 3-redirection so that it configures a brand new Ubuntu machine
#!/usr/bin/env bash
# installs a nginx on web-01
sudo apt update
sudo apt install -y nginx

sudo service nginx start

sudo echo "Hello World" | sudo tee /var/www/html/index

sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

sudo service nginx restart
