#!/usr/bin/env bash
# You answer file should be a Bash script containing commands
# to automatically configure a Ubuntu machine
# Using what you did with 1-install_nginx_web_server,
# write 3-redirection so that it configures a brand new Ubuntu machine

# Update the package repository
sudo apt update

# Install Nginx
sudo apt install -y nginx

# Start Nginx
sudo service nginx start

# Create an index.html file with "Hello World!"
sudo echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure redirection for /redirect_me
sudo sed -i '/server_name _;/a '\
    '	location /redirect_me {'\
    '		rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;'\
    '	}' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart

