#!/usr/bin/env bash
# set up a custom 404 page
# Update the package repository
sudo apt update

# Install Nginx
sudo apt install -y nginx

# Start Nginx
sudo service nginx start

sudo echo "Hello World!" | sudo tee /var/www/html/index

sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

# Create a custom 404 HTML page
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Modify the Nginx configuration to use the custom 404 page
sudo sed -i '/watch?v=QH2-TGUlwu4;\n   }/a \
	     error_page 404 /custom_404.html;\n\
	     location = /custom_404.html {\n\
		     internal;\n\
	     };\n' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart

