#!/usr/bin/env bash
# This script configures HAproxy on the lb-01 server

# add necessary environmen prerequisites
sudo apt update -y
sudo apt install -y --no-install-recommends software-properties-common

# app package repository source
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt update -y

# install haproxy
sudo apt-get install haproxy=2.0.\* -y

# enable haproxy init script
if [ ! -f /etc/default/haproxy.orig ]; then
    sudo cp /etc/default/haproxy /etc/default/haproxy.orig
fi
# sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy # make ENABLED=1


# make a backup of the original config file
if [ ! -f /etc/haproxy/haproxy.cfg.orig ]; then
    sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
fi

# Configure HAProxy
#sudo vi /etc/haproxy/haproxy.cfg

# Enable logging in HAProxy
#sudo vi /etc/rsyslog.conf

# restart service for config to take effect
sudo service haproxy restart
