#!/usr/bin/env bash
# generates a mysql dump and creates a compressed archive out of it

date=$(date +%d-%m-%Y)

sudo mysqldump -uroot -p"$1" --no-tablespaces --lock-tables --all-databases > backup.sql

tar -czvf "${date}.tar.gz" backup.sql
