#!/usr/bin/env bash
# This script pings an IP address passed as an argument.
# It accepts a string as an argument.
# It Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS}
#  if no argument passed
# It pings the IP 5 times.

if [ "$#" -eq 0 ];
    then 
        echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
        exit 1
    else
        ping -c 5 "$1"
        exit 0
fi
