#!/usr/bin/env bash
# This script displays a list of currently running processes.
# It shows all processes, for all users,
# including those which might not have a TTY, 
# Displays in a user-oriented format 
# Shows process hierarchy

# "    USER PID %CPU %MEM VSZ RSS TTY STAT START TIME COMMAND"
ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest