#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely
# with a sleep of 2 seconds between each iteration.

echo $$ > /tmp/infinity_pid

while true; do
  echo "To infinity and beyond"
  sleep 2
done
