#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal

echo $$ > /tmp/infinity_piid
# Function to handle SIGTERM signal
function handle_sigterm() {
  echo "I am invincible!!!"
  exit 0
}

# Register the SIGTERM signal handler
trap handle_sigterm SIGTERM

# Infinite loop with a sleep of 2 seconds
while true; do
  echo "To infinity and beyond"
  sleep 2
done
