#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd.
# Displays only the username, user ID, and Home directory path for each user
# Using a while loop

while IFS=: read -r username password userID groupID UserInfo HomeDirectory Shell;
do
    printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s\n" "$username" "$groupID" "$HomeDirectory" "$Shell" "$userID" "$password" "$UserInfo"
done < /etc/passwd
